# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: src/embedding.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(_runtime_version.Domain.PUBLIC, 6, 31, 1, "", "src/embedding.proto")
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x13src/embedding.proto\x12\tembedding"a\n\x10\x45mbedTextRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x12\n\nmax_length\x18\x02 \x01(\x05\x12\x11\n\tnormalize\x18\x03 \x01(\x08\x12\x18\n\x10pooling_strategy\x18\x04 \x01(\t"&\n\x11\x45mbedTextResponse\x12\x11\n\tembedding\x18\x01 \x03(\x02"w\n\x11\x45mbedBatchRequest\x12\r\n\x05texts\x18\x01 \x03(\t\x12\x12\n\nbatch_size\x18\x02 \x01(\x05\x12\x12\n\nmax_length\x18\x03 \x01(\x05\x12\x11\n\tnormalize\x18\x04 \x01(\x08\x12\x18\n\x10pooling_strategy\x18\x05 \x01(\t"!\n\x0f\x45mbeddingVector\x12\x0e\n\x06vector\x18\x01 \x03(\x02"D\n\x12\x45mbedBatchResponse\x12.\n\nembeddings\x18\x01 \x03(\x0b\x32\x1a.embedding.EmbeddingVector"\x07\n\x05\x45mpty"&\n\x11\x44imensionResponse\x12\x11\n\tdimension\x18\x01 \x01(\x05"D\n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x12\n\nmodel_name\x18\x02 \x01(\t\x12\x0e\n\x06\x64\x65vice\x18\x03 \x01(\t2\xaa\x02\n\x10\x45mbeddingService\x12\x46\n\tEmbedText\x12\x1b.embedding.EmbedTextRequest\x1a\x1c.embedding.EmbedTextResponse\x12I\n\nEmbedBatch\x12\x1c.embedding.EmbedBatchRequest\x1a\x1d.embedding.EmbedBatchResponse\x12G\n\x15GetEmbeddingDimension\x12\x10.embedding.Empty\x1a\x1c.embedding.DimensionResponse\x12:\n\x0bHealthCheck\x12\x10.embedding.Empty\x1a\x19.embedding.HealthResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "src.embedding_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_EMBEDTEXTREQUEST"]._serialized_start = 34
    _globals["_EMBEDTEXTREQUEST"]._serialized_end = 131
    _globals["_EMBEDTEXTRESPONSE"]._serialized_start = 133
    _globals["_EMBEDTEXTRESPONSE"]._serialized_end = 171
    _globals["_EMBEDBATCHREQUEST"]._serialized_start = 173
    _globals["_EMBEDBATCHREQUEST"]._serialized_end = 292
    _globals["_EMBEDDINGVECTOR"]._serialized_start = 294
    _globals["_EMBEDDINGVECTOR"]._serialized_end = 327
    _globals["_EMBEDBATCHRESPONSE"]._serialized_start = 329
    _globals["_EMBEDBATCHRESPONSE"]._serialized_end = 397
    _globals["_EMPTY"]._serialized_start = 399
    _globals["_EMPTY"]._serialized_end = 406
    _globals["_DIMENSIONRESPONSE"]._serialized_start = 408
    _globals["_DIMENSIONRESPONSE"]._serialized_end = 446
    _globals["_HEALTHRESPONSE"]._serialized_start = 448
    _globals["_HEALTHRESPONSE"]._serialized_end = 516
    _globals["_EMBEDDINGSERVICE"]._serialized_start = 519
    _globals["_EMBEDDINGSERVICE"]._serialized_end = 817
# @@protoc_insertion_point(module_scope)
