# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc
import warnings

import tests.embedding_pb2 as src_dot_embedding__pb2

GRPC_GENERATED_VERSION = "1.75.1"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + f" but the generated code in src/embedding_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class EmbeddingServiceStub(object):
    """Embedding gRPC service definition"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EmbedText = channel.unary_unary(
            "/embedding.EmbeddingService/EmbedText",
            request_serializer=src_dot_embedding__pb2.EmbedTextRequest.SerializeToString,
            response_deserializer=src_dot_embedding__pb2.EmbedTextResponse.FromString,
            _registered_method=True,
        )
        self.EmbedBatch = channel.unary_unary(
            "/embedding.EmbeddingService/EmbedBatch",
            request_serializer=src_dot_embedding__pb2.EmbedBatchRequest.SerializeToString,
            response_deserializer=src_dot_embedding__pb2.EmbedBatchResponse.FromString,
            _registered_method=True,
        )
        self.GetEmbeddingDimension = channel.unary_unary(
            "/embedding.EmbeddingService/GetEmbeddingDimension",
            request_serializer=src_dot_embedding__pb2.Empty.SerializeToString,
            response_deserializer=src_dot_embedding__pb2.DimensionResponse.FromString,
            _registered_method=True,
        )
        self.HealthCheck = channel.unary_unary(
            "/embedding.EmbeddingService/HealthCheck",
            request_serializer=src_dot_embedding__pb2.Empty.SerializeToString,
            response_deserializer=src_dot_embedding__pb2.HealthResponse.FromString,
            _registered_method=True,
        )


class EmbeddingServiceServicer(object):
    """Embedding gRPC service definition"""

    def EmbedText(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def EmbedBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetEmbeddingDimension(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_EmbeddingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "EmbedText": grpc.unary_unary_rpc_method_handler(
            servicer.EmbedText,
            request_deserializer=src_dot_embedding__pb2.EmbedTextRequest.FromString,
            response_serializer=src_dot_embedding__pb2.EmbedTextResponse.SerializeToString,
        ),
        "EmbedBatch": grpc.unary_unary_rpc_method_handler(
            servicer.EmbedBatch,
            request_deserializer=src_dot_embedding__pb2.EmbedBatchRequest.FromString,
            response_serializer=src_dot_embedding__pb2.EmbedBatchResponse.SerializeToString,
        ),
        "GetEmbeddingDimension": grpc.unary_unary_rpc_method_handler(
            servicer.GetEmbeddingDimension,
            request_deserializer=src_dot_embedding__pb2.Empty.FromString,
            response_serializer=src_dot_embedding__pb2.DimensionResponse.SerializeToString,
        ),
        "HealthCheck": grpc.unary_unary_rpc_method_handler(
            servicer.HealthCheck,
            request_deserializer=src_dot_embedding__pb2.Empty.FromString,
            response_serializer=src_dot_embedding__pb2.HealthResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler("embedding.EmbeddingService", rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("embedding.EmbeddingService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class EmbeddingService(object):
    """Embedding gRPC service definition"""

    @staticmethod
    def EmbedText(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/embedding.EmbeddingService/EmbedText",
            src_dot_embedding__pb2.EmbedTextRequest.SerializeToString,
            src_dot_embedding__pb2.EmbedTextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def EmbedBatch(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/embedding.EmbeddingService/EmbedBatch",
            src_dot_embedding__pb2.EmbedBatchRequest.SerializeToString,
            src_dot_embedding__pb2.EmbedBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetEmbeddingDimension(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/embedding.EmbeddingService/GetEmbeddingDimension",
            src_dot_embedding__pb2.Empty.SerializeToString,
            src_dot_embedding__pb2.DimensionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def HealthCheck(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/embedding.EmbeddingService/HealthCheck",
            src_dot_embedding__pb2.Empty.SerializeToString,
            src_dot_embedding__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
