# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from tests import reranker_pb2 as tests_dot_reranker__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in tests/reranker_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RerankerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Rerank = channel.unary_unary(
                '/reranker.RerankerService/Rerank',
                request_serializer=tests_dot_reranker__pb2.RerankRequest.SerializeToString,
                response_deserializer=tests_dot_reranker__pb2.RerankResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/reranker.RerankerService/HealthCheck',
                request_serializer=tests_dot_reranker__pb2.Empty.SerializeToString,
                response_deserializer=tests_dot_reranker__pb2.HealthResponse.FromString,
                _registered_method=True)


class RerankerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Rerank(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RerankerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Rerank': grpc.unary_unary_rpc_method_handler(
                    servicer.Rerank,
                    request_deserializer=tests_dot_reranker__pb2.RerankRequest.FromString,
                    response_serializer=tests_dot_reranker__pb2.RerankResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=tests_dot_reranker__pb2.Empty.FromString,
                    response_serializer=tests_dot_reranker__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'reranker.RerankerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('reranker.RerankerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RerankerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Rerank(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/reranker.RerankerService/Rerank',
            tests_dot_reranker__pb2.RerankRequest.SerializeToString,
            tests_dot_reranker__pb2.RerankResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/reranker.RerankerService/HealthCheck',
            tests_dot_reranker__pb2.Empty.SerializeToString,
            tests_dot_reranker__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
